name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4", head]
        postgres: [13, 14, 15, 16]
        gemfile:
          [
            gemfiles/activerecord60.gemfile,
            gemfiles/activerecord61.gemfile,
            gemfiles/activerecord70.gemfile,
            gemfiles/activerecord71.gemfile,
            gemfiles/activerecord72.gemfile,
            gemfiles/activerecord80.gemfile,
          ]
        exclude:
          # Rails 7.2 requires Ruby 3.1 or higher
          - ruby: "2.7"
            gemfile: gemfiles/activerecord72.gemfile
          - ruby: "2.7"
            gemfile: gemfiles/activerecord80.gemfile
          - ruby: "3.0"
            gemfile: gemfiles/activerecord72.gemfile
          - ruby: "3.0"
            gemfile: gemfiles/activerecord80.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ matrix.postgres }}
          database: pghero_test
          config: |
            shared_preload_libraries = 'pg_stat_statements'
      - run: bundle exec rake test
